### ISSUE TITLE
Selecting Output Power via RC Channel?

### ISSUE THREAD

**Issue by TobiasBales** [openLRSng/openLRSng#32] opened 2013-11-17 15:04 UTC
After using switching from EzUHF to a hawkeye lrs system
using openlrsng there is one thing I am missing.
Being able to use a switch to select between 2 (or 3) output power modes.

Is there an interest in adding this and getting it into the main repo?
If so I would probably do that.

The idea is to have a 2 or 3 position switch (I would prefer 3) to switch between
200mW, 600mW and 1W which can be useful to recover the plane in case of a failsafe etc.

Any opinions on this?

**Comment by csurf** [comment] 2018-01-09 23:34
@mikeller 
we could probably get this setup, but I'm not sure if it's worth it. I personally wouldn't have a need for this, but others might. 

It appears that your multiproto has the ability to change RF power, so perhaps legacy users might find something like this useful. dunno...

thoughts?

**Comment by mikeller** [comment] 2018-01-10 00:40
Yeah, I think this has mostly been superseded by the Multiprotocol support. I think we should close this.

**Comment by csurf** [comment] 2018-01-10 00:43
agreed.

**Closed** 2018-01-10 00:47 UTC

**Comment by geofrancis** [comment] 2018-01-10 16:07
Power switching is already supported by a switch on the module itsself.

**Comment by marcmerlin** [comment] 2018-01-10 19:55
@geofrancis and it doesn't work for what it's worth, at least if never worked for me.

**Comment by mikeller** [comment] 2018-01-10 20:04
@marcmerlin: It seems to be working well on the orangeRX modules - but you have to solder on your own switch for it.

These days, the most comfortable way for this is to use Multiprotocol, and use the menu on the TX to adjust your power.

**Comment by geofrancis** [comment] 2018-01-10 20:30
the problem is you cant change the PA power on the modules, your just changing the input to the PA, i made a module with adjustable power before, basically switching the PA between 3.3v and 6v, normally this would reboot the module but with a large capacitor it slowed down the voltage change enough that it could be switched on the fly.
